baseURL = "https://robojumper.github.io"
title = "Too Real"

theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "en"  # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en"  # For HTML page, now support: en, zh-hans, zh-hant, ja, nl

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10

[outputFormats]
  [outputFormats.SearchIndex]
    isPlainText = true
    notAlternative = true
    mediaType = "application/json"
    path = "/search/"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
  post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  author = "robojumper" # You can also set author in post front matter individually
  subTitle = "robojumper's blog about the Unreal Engine and XCOM 2 modding."

  # Source URL of the website, will appear in the footer
  sourceURL = "https://github.com/robojumper/robojumper.github.io"

  # Word counter and read time indicator in post metadata
  #showWordCounter = true
  showReadTime = true

  # License in the footer
  showLicenseInFooter = false

  # License at the end of each post
  showLicense = true
  showToc = true

  # Copyright
  copyrightStartYear = "2020"

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "robojumper's blog about the Unreal Engine and XCOM 2 modding."
  images = ["img/profile.png"] # This will use the image called og.png in static/img folder

  # Posts shown in homepage
  mainSections = ["too-real"]

  # License
  license = "CC BY"
  licenseLink = "https://creativecommons.org/licenses/by/4.0/"

  # Comments
  # utterances, see: https://utteranc.es/
  utterancesRepo = "robojumper/robojumper.github.io"
  utterancesIssueTerm = "pathname"

  # custom lazyload placeholder
  # 16:9
  lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

  # Let images display in full brightness under dark mode
  # disableDarkImage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[taxonomies]
  tag = "tags"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/robojumper"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/robojumper_"
    weight = 2
